name: mvn projct
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout
       uses: actions/checkout@v6.0.1
     - name : for test
       run: mvn test
     - name: exucute app
       run: mvn -B package
     - name: for listing
       run: ls -lh target/
